function cardsRoll() {
const card1 = document.createElement('img')
const card2 = document.createElement('img')
const card3 = document.createElement('img')
const card4 = document.createElement('img')
const card5 = document.createElement('img')
const card6 = document.createElement('img')
const card7 = document.createElement('img')
const card8 = document.createElement('img')
const card9 = document.createElement('img')
const card10 = document.createElement('img')
const card11 = document.createElement('img')
const card12 = document.createElement('img')
const card13 = document.createElement('img')
const card14 = document.createElement('img')
const card15 = document.createElement('img')
const card16 = document.createElement('img')
const card17 = document.createElement('img')
const card18 = document.createElement('img')
const card19 = document.createElement('img')
const card20 = document.createElement('img')
const card21 = document.createElement('img')
const card22 = document.createElement('img')
const card23 = document.createElement('img')
const card24 = document.createElement('img')
const card25 = document.createElement('img')
const card26 = document.createElement('img')
const card27 = document.createElement('img')
const card28 = document.createElement('img')
const card29 = document.createElement('img')
const card30 = document.createElement('img')
const card31 = document.createElement('img')
const card32 = document.createElement('img')
const card33 = document.createElement('img')
const card34 = document.createElement('img')
const card35 = document.createElement('img')
const card36 = document.createElement('img')

card1.setAttribute('src','./cards/6byb.jpg')
card2.setAttribute('src','./cards/6cher.jpg')
card3.setAttribute('src','./cards/6pic.jpg')
card4.setAttribute('src','./cards/6kre.jpg')
card5.setAttribute('src','./cards/7byb.jpg')
card6.setAttribute('src','./cards/7cher.jpg')
card7.setAttribute('src','./cards/7pic.jpg')
card8.setAttribute('src','./cards/7kre.jpg')
card9.setAttribute('src','./cards/8byb.jpg')
card10.setAttribute('src','./cards/8cher.jpg')
card11.setAttribute('src','./cards/8kre.jpg')
card12.setAttribute('src','./cards/8pic.jpg')
card13.setAttribute('src','./cards/9pic.jpg')
card14.setAttribute('src','./cards/9kre.jpg')
card15.setAttribute('src','./cards/9byb.jpg')
card16.setAttribute('src','./cards/9cher.jpg')
card17.setAttribute('src','./cards/10pic.jpg')
card18.setAttribute('src','./cards/10kre.jpg')
card19.setAttribute('src','./cards/10byb.jpg')
card20.setAttribute('src','./cards/10cher.jpg')
card21.setAttribute('src','./cards/Jpic.jpg')
card22.setAttribute('src','./cards/Jkre.jpg')
card23.setAttribute('src','./cards/Jbyb.jpg')
card24.setAttribute('src','./cards/Jcher.jpg')
card25.setAttribute('src','./cards/Dpic.jpg')
card26.setAttribute('src','./cards/Dkre.jpg')
card27.setAttribute('src','./cards/Dbyb.jpg')
card28.setAttribute('src','./cards/Dcher.jpg')
card29.setAttribute('src','./cards/Kpic.jpg')
card30.setAttribute('src','./cards/Kkre.jpg')
card31.setAttribute('src','./cards/Kbyb.jpg')
card32.setAttribute('src','./cards/Kcher.jpg')
card33.setAttribute('src','./cards/Tpic.jpg')
card34.setAttribute('src','./cards/Tkre.jpg')
card35.setAttribute('src','./cards/Tbyb.jpg')
card36.setAttribute('src','./cards/Tcher.jpg')

let cardShacker = [card1, card2, card3, card4, card5, card6, card7, card8, card9, card10, card11, card12, card13, card14, card15, card16, card17, card18, card19, card20, card21, card22, card23, card24, card25, card26, card27, card28, card29, card30, card31, card32, card33, card34, card35, card36]

cardShacker.forEach(element => {
    mainBar.appendChild(element)
    element.classList.add('cardBack')
});
}